Migrating r130
maximeq/image-skeletonizer pull request #4
Opened 2024-07-03 10:59 UTC by matteoJeulin

2024-07-19 15:23 UTC, ersbeth requested changes
Partial review, I can't see diffs for source files. I'll seek for another way to finish the review.

2024-07-19 15:23 UTC, ersbeth commented on package.json
Add the "types" field like in other repositories (I'm not talking about the "type" field which is correct)

2024-07-19 15:23 UTC, ersbeth commented on rollup.config.js
> +    // TODO: uncomment this when package is fully ported to TS
Uncomment this as stated

2024-07-19 15:23 UTC, ersbeth commented on rollup.config.js
>  const MODULE_NAME = "ImageSkeletonizer";
I think this var is not needed anymore

2024-07-19 15:23 UTC, ersbeth commented on rollup.config.js
>  const MODULE_FILENAME = "image-skeletonizer";
same

2024-07-19 15:23 UTC, ersbeth commented on rollup.config.js
>  const DIST = "./dist";
same

2024-07-19 16:31 UTC, ersbeth requested changes

2024-07-19 16:31 UTC, ersbeth commented on src/Image/BinaryImage.ts
> + *  TODO : tolerance is unused, see if it is useful
So did you find it ?

2024-07-19 16:31 UTC, ersbeth commented on src/Image/IntDistanceImage.ts
> +     *  @return {ImageData} A grey scale ImageData to visualize the distances.
remove type

2024-07-22 13:14 UTC, ersbeth requested changes

2024-07-22 13:14 UTC, ersbeth commented on src/Image/IntDistanceImage.ts
> +            throw "IntDistanceImage Error : source must be an instance of BinaryImage";
format error message

2024-07-22 13:14 UTC, ersbeth commented on src/Skeletonizer/CapsuleDistance.ts
> -            Math.max( // Necessary because of rounded errors, pyth result can be <0 and this causes sqrt to return NaN...
comment was lost

2024-07-22 13:14 UTC, ersbeth commented on src/Skeletonizer/SkeletonImage.ts
>  "use strict";
Remove all "use strict"  in all files: this is by default when using ESM syntax.

2024-07-22 13:14 UTC, ersbeth commented on src/Skeletonizer/Skeletonizer.ts
> -/**
Comment was lost

2024-07-22 14:09 UTC, matteoJeulin commented on src/Image/BinaryImage.ts
> + *  TODO : tolerance is unused, see if it is useful
It is used when calling the function but is useless in the function itself

2024-07-25 12:41 UTC, ersbeth reviewed
Last changes look good to me.

2024-07-25 15:00 UTC, ersbeth reviewed
Changes look good to me

2024-07-25 15:02 UTC, ersbeth approved these changes

2024-07-25 15:03 UTC, merged